version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: save_ip
      DB_HOST: mongodb
      DB_PORT: 27017

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root